# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.array([5 for _ in range(10)], dtype = float)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [8]:
np.array([x for x in range(10,51)])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
lst1 = [x for x in range(10,51) if x%2 == 0]
print(lst1)
np.array([lst1])

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


array([[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40,
        42, 44, 46, 48, 50]])

#### Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [40]:
np.random.rand()

0.08164924245165772

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

In [46]:
from numpy.random import randn as ra
np.array(ra(25))

array([ 0.73826088,  0.20324139, -1.64091055, -0.78392891, -1.05828186,
       -0.63364845,  0.7205128 ,  0.04441712, -1.11080291, -1.4697122 ,
        0.60097336, -2.33782104, -0.69289442,  0.24915084, -0.4495707 ,
       -3.09196571,  0.67944321,  0.22168883,  0.5895389 , -0.41861029,
       -0.77741603,  0.65087056, -1.38980743,  0.22463422,  0.76575201])

#### Create the following matrix:

array([[0.47325185, 0.31687143, 0.92315798, 0.00944664, 0.60830481,
        0.47149244, 0.79730795, 0.72197131, 0.84899411, 0.01795184],
       [0.57900727, 0.34508023, 0.48016543, 0.99348081, 0.06871019,
        0.31279884, 0.55701429, 0.98209127, 0.51928253, 0.92712081],
       [0.62565429, 0.80846004, 0.72829608, 0.34980847, 0.2327374 ,
        0.47676367, 0.38464416, 0.5483618 , 0.63090987, 0.36734357],
       [0.47504607, 0.6957894 , 0.10041094, 0.83642747, 0.109461  ,
        0.37350456, 0.18693862, 0.83277221, 0.27106925, 0.39778378],
       [0.77510687, 0.78144895, 0.35545704, 0.23139187, 0.87181658,
        0.46630382, 0.31662621, 0.2948518 , 0.52938676, 0.97693867],
       [0.04279191, 0.7529686 , 0.27601624, 0.037062  , 0.49163982,
        0.08637015, 0.17704648, 0.02366608, 0.19145927, 0.38069567],
       [0.25340951, 0.8950335 , 0.23507032, 0.18247659, 0.57591731,
        0.97841964, 0.89265674, 0.48002304, 0.40070118, 0.50849625],
       [0.6112385 , 0.29325072, 0.0759372

In [48]:
np.array(np.random.rand(10,10))

array([[0.49615562, 0.45162558, 0.25245976, 0.80159348, 0.60947156,
        0.33233288, 0.3924379 , 0.04923103, 0.09990073, 0.64695039],
       [0.77713298, 0.83182932, 0.19171336, 0.79909246, 0.57695951,
        0.41839134, 0.97640001, 0.71847198, 0.55845754, 0.16049523],
       [0.50380086, 0.54598842, 0.2857865 , 0.47522604, 0.01520771,
        0.67871071, 0.55631915, 0.47266415, 0.05174003, 0.25000907],
       [0.75202522, 0.66546483, 0.6876096 , 0.30150504, 0.58852455,
        0.78366184, 0.42886498, 0.62615255, 0.72308524, 0.46516845],
       [0.69374464, 0.05933913, 0.633374  , 0.95780172, 0.63380456,
        0.35347705, 0.15408925, 0.80485586, 0.28950498, 0.76155538],
       [0.86730151, 0.6079766 , 0.49665356, 0.42399826, 0.62550231,
        0.25671575, 0.88858697, 0.04562656, 0.9308598 , 0.73498014],
       [0.41854507, 0.81608767, 0.36289209, 0.18448258, 0.68765503,
        0.70228473, 0.84636772, 0.37413315, 0.64741835, 0.07845848],
       [0.92311675, 0.1645371 , 0.5130928

#### Create an array of 20 linearly spaced points between 0 and 1:

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [49]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
lst = [x for x in range(1,26)]
np.array(lst).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [89]:
#print(dir(np.array([x for x in range(12,27)]).reshape(3,5)))
narr = np.array([x for x in range(12,27)]).reshape(3,5)
np.delete(narr,4,1)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [53]:
np.array([2,7,12]).reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [56]:
np.array([x for x in range(21,26)])

array([21, 22, 23, 24, 25])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
np.array([x for x in range(16,26)]).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

In [63]:
#print(dir(np.array([x for x in range(16,26)]).reshape(2,5)))
np.array([x for x in range(16,26)]).reshape(2,5).sum()

205

#### Get the standard deviation of the values in mat

7.211102550927978

In [ ]:
np.array([x for x in range(16,26)]).reshape(2,5).std()

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

In [66]:
np.array([x for x in range(16,26)]).reshape(2,5).sum(axis = 0)

array([37, 39, 41, 43, 45])

# Great Job!